name: Deploy 🚀

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::211125562192:role/GitHubAssumeRole' || 'arn:aws:iam::891377366124:role/GitHubAssumeRole' }}
          aws-region: us-east-1

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm build --mode ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

      - name: Deploy
        run: |
          # Upload to S3
          aws s3 sync dist/ s3://${{ github.ref == 'refs/heads/main' && 'client-dashboard-bucket-20240612194953021800000001' || 'client-dashboard-bucket-20240612193909644100000001' }} --delete

          # Invalidate CloudFront cache
          aws cloudfront create-invalidation --distribution-id ${{ github.ref == 'refs/heads/main' && 'E18WT1BH9N6CZG' || 'EEUTUZS1J24KA' }} --paths "/*"
